"""The table module for the pyformance analytics code."""
# ruff: noqa: F401
from .annualized_returns import AnnualizedReturns
from .arbitrary import Arbitrary
from .autocorrelation import autocorrelation
from .calendar_returns import calendar_returns
from .capture_ratios import CaptureRatios
from .correlation import correlation
from .distributions import distributions
from .downside_risk import DownsideRisk
from .downside_risk_ratio import downside_risk_ratio
from .drawdowns import drawdowns
from .drawdowns_ratio import DrawdownsRatio
from .higher_moments import HigherMoments
from .information_ratio import information_ratio
from .prob_out_performance import ProbOutPerformance
from .rolling_periods import RollingPeriods
from .SFM import SFM
from .specific_risk import SpecificRisk
from .stats import stats
from .trailing_periods_rel import TrailingPeriodsRel
from .up_down_ratios import up_down_ratios
from .variability import variability
