"""The table module for the pyformance analytics code."""
from .annualized_returns import annualized_returns
from .arbitrary import arbitrary
from .autocorrelation import autocorrelation
from .calendar_returns import calendar_returns
from .capture_ratios import capture_ratios
from .up_down_ratios import up_down_ratios
from .correlation import correlation
from .distributions import distributions
from .downside_risk import downside_risk
from .downside_risk_ratio import downside_risk_ratio
from .drawdowns import drawdowns
from .drawdowns_ratio import drawdowns_ratio
from .higher_moments import higher_moments
from .information_ratio import information_ratio
from .prob_out_performance import prob_out_performance
from .rolling_periods import rolling_periods
from .trailing_periods_rel import trailing_periods_rel
from .SFM import sfm
from .specific_risk import specific_risk
from .stats import stats
from .variability import variability